[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_staking_new = "9rJMCxX5tpXwx8M42Truai3RTmqGA2vsDUP1mTV9QNFY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
script = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"